_BASE_: "../_base_/chairs_baseline.yaml"
DATA:
  BATCH_SIZE: 4
  NUM_WORKERS: 12
  NORM_PARAMS: {"use": True, "mean":[127.5, 127.5, 127.5], "std":[127.5, 127.5, 127.5]}
  APPEND_VALID_MASK: True
  TRAIN_DATASET:
    FlyingChairs:
      AUGMENTATION:
        USE: False
      CROP: 
        USE: False
        SIZE: [256, 256]
        TYPE: "random"
  VAL_DATASET:
    FlyingChairs:
      PADDING: 1
      CROP: 
        USE: True
        SIZE: [256, 256]
        TYPE: "center"
SCHEDULER:
  USE: True
  NAME: OneCycleLR
  PARAMS:
    max_lr: 0.0001
    total_steps: 100100
    pct_start: 0.05
    cycle_momentum: False
    anneal_strategy: linear
    div_factor: 250
CRITERION:
  CUSTOM: True
  NAME: MultiScaleLossUncertain
  PARAMS:
    norm: "l2" 
    weights: [1.0]
    average: "mean"
    resize_flow: "upsample"
EPOCHS: null
NUM_STEPS: 100100
LOG_DIR: "./logs"
CKPT_DIR: "./ckpts"
LOG_ITERATIONS_INTERVAL: 100
CKPT_INTERVAL: 5000
VALIDATE_INTERVAL: 1000
VALIDATE_ON: metric
DISTRIBUTED:
  USE: True
MIXED_PRECISION: True